[default]
port = 8000
address = "127.0.0.1"

[default.databases]
neptis_db = { url = "postgres://postgres:XXXXXXXXXX!@localhost/neptis" }

[release]
address = "0.0.0.0"  # Allow external access
log_level = "normal"